### ISSUE TITLE
ZNR rotation checklist

### ISSUE THREAD

**Issue by vorpal-buildbot** [PennyDreadfulMTG/Penny-Dreadful-Tools#7907]
https://pennydreadfulmagic.com/admin/rotation/

- [x] upload legal_cards.txt to S3
- [x] upload ZNR_legal_cards.txt to S3
- [x] ping scryfall
- [x] email mtggoldfish
- [ ] ping tappedout
- [x] restart discordbot
- [x] run post_rotation

Reported on rotation by rotation script
