### ISSUE TITLE
KHM rotation checklist

### ISSUE THREAD

**Issue by vorpal-buildbot** [PennyDreadfulMTG/Penny-Dreadful-Tools#8287]
https://pennydreadfulmagic.com/admin/rotation/

- [x] upload legal_cards.txt to S3
- [x] upload KHM_legal_cards.txt to S3
- [x] ping scryfall
- [x] email mtggoldfish
- [ ] ping tappedout
- [x] run post_rotation

Reported on rotation by rotation script
